# User config
author: "Justin Alejandro"
tagline: "Designer"
description: "I'm Justin Alejandro - designer specializing in building and supporting brands in the digital space."
keywords: "Justin Alejandro, design, graphic design, web design, web development, front end, HTML, CSS, Photoshop, Illustrator"
email: "hello@justinalejandro.com"
linkedin: "https://ca.linkedin.com/in/justin-alejandro"
twitter: "https://twitter.com/justinalejandro"
instagram: "https://www.instagram.com/_jay_eh/?hl=en"

# Site config
url: https://jay-eh.github.io
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
